### ISSUE TITLE
[INCOMPLETE] Bookmarklet

### ISSUE THREAD

**Issue by sergeevabc** [brysbroughton/native_toc#1]
Dear @brysbroughton,
Could you be so kind to tell how to transform it into bookmarklet (if possible) to invoke while browsing?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by brysbroughton** [comment]
Hi @sergeevabc, sorry for the late response. That's a good idea to have a toc bookmarklet. I tried running the script through google closure, replacing non-url safe characters, and pasting the result in to an anchor, but this is not working. You can see this in the [bookmarklet branch](https://github.com/brysbroughton/native_toc/tree/bookmarklet).

**Comment by brysbroughton** [comment]
Also, before using this on your pages, check the other issue that I just opened. There are still some cases that can break the script. Sorry this is not ready to go, but I'll keep working on it :)

**Comment by sergeevabc** [comment]
It just does not work. Tried [this][1] and [that][2] bookmarklet generators as well.

Seems [Marc Hoyois’ HTML5 outliner][3] is still the best way to generate TOCs.

[1]: http://ted.mielczarek.org/code/mozilla/bookmarklet.html
[2]: http://bookmarklets.org/maker/
[3]: https://hoyois.github.io/
